In [1]:
%cd ..
import sys
sys.path.append("src")

/auto/sahara/namib/home/macgregor/amplicon/workflow_16s

In [2]:
from workflow_16s.downstream._01_load_data import DataLoader
from workflow_16s.downstream._02_transform_tables import DataProcessor
from workflow_16s.config import get_config # type: ignore
config = get_config()

13:48:52 INFO     Logging initialised →
                  /auto/sahara/namib/home/macgregor/amplicon/workflow_16s/logs/2025-09-22_134852.log

/usr2/people/macgregor/amplicon/workflow_16s/config/config.yaml

In [3]:
%%capture
loader = DataLoader(config)
data_object = loader.run()

INFO:choreographer.browsers.chromium:Chromium init'ed with kwargs {}
INFO:choreographer.browsers.chromium:Found chromium path: /auto/sahara/namib/home/macgregor/miniconda3/envs/workflow_16s/lib/python3.10/site-packages/choreographer/cli/browser_exe/chrome-linux64/chrome
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmpx80tz73q.
INFO:choreographer.browser_async:Opening browser.
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmpu8bjhksw.
INFO:choreographer.browsers.chromium:Temporary directory at: /opt/tmp/tmpu8bjhksw
INFO:kaleido.kaleido:Conforming 1 to file:///opt/tmp/tmpx80tz73q/index.html
INFO:kaleido.kaleido:Waiting on all navigates
INFO:kaleido.kaleido:All navigates done, putting them all in queue.
INFO:kaleido.kaleido:Getting tab from queue (has 1)
INFO:kaleido.kaleido:Got D039
INFO:kaleido._kaleido_tab:Processing fig.png
INFO:kaleido._kaleido_tab:Sending big command for fig.png.
INFO:kaleido._kaleido_tab:Sent big command for fig.png.
INFO:kaleido.kaleido:Reloading tab D039 before return.
INFO:kaleido.kaleido:Putting tab D039 back (queue size: 0).
INFO:kaleido.kaleido:Waiting for all cleanups to finish.
INFO:kaleido.kaleido:Exiting Kaleido
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.browsers.chromium:Chromium init'ed with kwargs {}
INFO:choreographer.browsers.chromium:Found chromium path: /auto/sahara/namib/home/macgregor/miniconda3/envs/workflow_16s/lib/python3.10/site-packages/choreographer/cli/browser_exe/chrome-linux64/chrome
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmpov0kdrse.
INFO:choreographer.browser_async:Opening browser.
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmpdg0h9qoo.
INFO:choreographer.browsers.chromium:Temporary directory at: /opt/tmp/tmpdg0h9qoo
INFO:kaleido.kaleido:Conforming 1 to file:///opt/tmp/tmpov0kdrse/index.html
INFO:kaleido.kaleido:Waiting on all navigates
INFO:kaleido.kaleido:All navigates done, putting them all in queue.
INFO:kaleido.kaleido:Getting tab from queue (has 1)
INFO:kaleido.kaleido:Got 432C
INFO:kaleido._kaleido_tab:Processing fig.png
INFO:kaleido._kaleido_tab:Sending big command for fig.png.
INFO:kaleido._kaleido_tab:Sent big command for fig.png.
INFO:kaleido.kaleido:Reloading tab 432C before return.
INFO:kaleido.kaleido:Putting tab 432C back (queue size: 0).
INFO:kaleido.kaleido:Waiting for all cleanups to finish.
INFO:kaleido.kaleido:Exiting Kaleido
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.browsers.chromium:Chromium init'ed with kwargs {}
INFO:choreographer.browsers.chromium:Found chromium path: /auto/sahara/namib/home/macgregor/miniconda3/envs/workflow_16s/lib/python3.10/site-packages/choreographer/cli/browser_exe/chrome-linux64/chrome
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmp8c76p700.
INFO:choreographer.browser_async:Opening browser.
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmpy8qu4_p5.
INFO:choreographer.browsers.chromium:Temporary directory at: /opt/tmp/tmpy8qu4_p5
INFO:kaleido.kaleido:Conforming 1 to file:///opt/tmp/tmp8c76p700/index.html
INFO:kaleido.kaleido:Waiting on all navigates
INFO:kaleido.kaleido:All navigates done, putting them all in queue.
INFO:kaleido.kaleido:Getting tab from queue (has 1)
INFO:kaleido.kaleido:Got 6AA5
INFO:kaleido._kaleido_tab:Processing fig.png
INFO:kaleido._kaleido_tab:Sending big command for fig.png.
INFO:kaleido._kaleido_tab:Sent big command for fig.png.
INFO:kaleido.kaleido:Reloading tab 6AA5 before return.
INFO:kaleido.kaleido:Putting tab 6AA5 back (queue size: 0).
INFO:kaleido.kaleido:Waiting for all cleanups to finish.
INFO:kaleido.kaleido:Exiting Kaleido
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.browsers.chromium:Chromium init'ed with kwargs {}
INFO:choreographer.browsers.chromium:Found chromium path: /auto/sahara/namib/home/macgregor/miniconda3/envs/workflow_16s/lib/python3.10/site-packages/choreographer/cli/browser_exe/chrome-linux64/chrome
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmpoet8r9t9.
INFO:choreographer.browser_async:Opening browser.
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmp8y2z5xrt.
INFO:choreographer.browsers.chromium:Temporary directory at: /opt/tmp/tmp8y2z5xrt
INFO:kaleido.kaleido:Conforming 1 to file:///opt/tmp/tmpoet8r9t9/index.html
INFO:kaleido.kaleido:Waiting on all navigates
INFO:kaleido.kaleido:All navigates done, putting them all in queue.
INFO:kaleido.kaleido:Getting tab from queue (has 1)
INFO:kaleido.kaleido:Got C66C
INFO:kaleido._kaleido_tab:Processing fig.png
INFO:kaleido._kaleido_tab:Sending big command for fig.png.
INFO:kaleido._kaleido_tab:Sent big command for fig.png.
INFO:kaleido.kaleido:Reloading tab C66C before return.
INFO:kaleido.kaleido:Putting tab C66C back (queue size: 0).
INFO:kaleido.kaleido:Waiting for all cleanups to finish.
INFO:kaleido.kaleido:Exiting Kaleido
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.browsers.chromium:Chromium init'ed with kwargs {}
INFO:choreographer.browsers.chromium:Found chromium path: /auto/sahara/namib/home/macgregor/miniconda3/envs/workflow_16s/lib/python3.10/site-packages/choreographer/cli/browser_exe/chrome-linux64/chrome
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmpurwuukk2.
INFO:choreographer.browser_async:Opening browser.
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmpzenlsdn5.
INFO:choreographer.browsers.chromium:Temporary directory at: /opt/tmp/tmpzenlsdn5
INFO:kaleido.kaleido:Conforming 1 to file:///opt/tmp/tmpurwuukk2/index.html
INFO:kaleido.kaleido:Waiting on all navigates
INFO:kaleido.kaleido:All navigates done, putting them all in queue.
INFO:kaleido.kaleido:Getting tab from queue (has 1)
INFO:kaleido.kaleido:Got 6B03
INFO:kaleido._kaleido_tab:Processing fig.png
INFO:kaleido._kaleido_tab:Sending big command for fig.png.
INFO:kaleido._kaleido_tab:Sent big command for fig.png.
INFO:kaleido.kaleido:Reloading tab 6B03 before return.
INFO:kaleido.kaleido:Putting tab 6B03 back (queue size: 0).
INFO:kaleido.kaleido:Waiting for all cleanups to finish.
INFO:kaleido.kaleido:Exiting Kaleido
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.browsers.chromium:Chromium init'ed with kwargs {}
INFO:choreographer.browsers.chromium:Found chromium path: /auto/sahara/namib/home/macgregor/miniconda3/envs/workflow_16s/lib/python3.10/site-packages/choreographer/cli/browser_exe/chrome-linux64/chrome
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmpd1feijy4.
INFO:choreographer.browser_async:Opening browser.
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmprng3s3xo.
INFO:choreographer.browsers.chromium:Temporary directory at: /opt/tmp/tmprng3s3xo
INFO:kaleido.kaleido:Conforming 1 to file:///opt/tmp/tmpd1feijy4/index.html
INFO:kaleido.kaleido:Waiting on all navigates
INFO:kaleido.kaleido:All navigates done, putting them all in queue.
INFO:kaleido.kaleido:Getting tab from queue (has 1)
INFO:kaleido.kaleido:Got B842
INFO:kaleido._kaleido_tab:Processing fig.png
INFO:kaleido._kaleido_tab:Sending big command for fig.png.
INFO:kaleido._kaleido_tab:Sent big command for fig.png.
INFO:kaleido.kaleido:Reloading tab B842 before return.
INFO:kaleido.kaleido:Putting tab B842 back (queue size: 0).
INFO:kaleido.kaleido:Waiting for all cleanups to finish.
INFO:kaleido.kaleido:Exiting Kaleido
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.browsers.chromium:Chromium init'ed with kwargs {}
INFO:choreographer.browsers.chromium:Found chromium path: /auto/sahara/namib/home/macgregor/miniconda3/envs/workflow_16s/lib/python3.10/site-packages/choreographer/cli/browser_exe/chrome-linux64/chrome
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmpv5hh8f3_.
INFO:choreographer.browser_async:Opening browser.
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmpyyq7ckn3.
INFO:choreographer.browsers.chromium:Temporary directory at: /opt/tmp/tmpyyq7ckn3
INFO:kaleido.kaleido:Conforming 1 to file:///opt/tmp/tmpv5hh8f3_/index.html
INFO:kaleido.kaleido:Waiting on all navigates
INFO:kaleido.kaleido:All navigates done, putting them all in queue.
INFO:kaleido.kaleido:Getting tab from queue (has 1)
INFO:kaleido.kaleido:Got F451
INFO:kaleido._kaleido_tab:Processing fig.png
INFO:kaleido._kaleido_tab:Sending big command for fig.png.
INFO:kaleido._kaleido_tab:Sent big command for fig.png.
INFO:kaleido.kaleido:Reloading tab F451 before return.
INFO:kaleido.kaleido:Putting tab F451 back (queue size: 0).
INFO:kaleido.kaleido:Waiting for all cleanups to finish.
INFO:kaleido.kaleido:Exiting Kaleido
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.browsers.chromium:Chromium init'ed with kwargs {}
INFO:choreographer.browsers.chromium:Found chromium path: /auto/sahara/namib/home/macgregor/miniconda3/envs/workflow_16s/lib/python3.10/site-packages/choreographer/cli/browser_exe/chrome-linux64/chrome
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmpla1y5mim.
INFO:choreographer.browser_async:Opening browser.
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmpm0nx_7w1.
INFO:choreographer.browsers.chromium:Temporary directory at: /opt/tmp/tmpm0nx_7w1
INFO:kaleido.kaleido:Conforming 1 to file:///opt/tmp/tmpla1y5mim/index.html
INFO:kaleido.kaleido:Waiting on all navigates
INFO:kaleido.kaleido:All navigates done, putting them all in queue.
INFO:kaleido.kaleido:Getting tab from queue (has 1)
INFO:kaleido.kaleido:Got 9B76
INFO:kaleido._kaleido_tab:Processing fig.png
INFO:kaleido._kaleido_tab:Sending big command for fig.png.
INFO:kaleido._kaleido_tab:Sent big command for fig.png.
INFO:kaleido.kaleido:Reloading tab 9B76 before return.
INFO:kaleido.kaleido:Putting tab 9B76 back (queue size: 0).
INFO:kaleido.kaleido:Waiting for all cleanups to finish.
INFO:kaleido.kaleido:Exiting Kaleido
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.browsers.chromium:Chromium init'ed with kwargs {}
INFO:choreographer.browsers.chromium:Found chromium path: /auto/sahara/namib/home/macgregor/miniconda3/envs/workflow_16s/lib/python3.10/site-packages/choreographer/cli/browser_exe/chrome-linux64/chrome
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmpf2vsa1cl.
INFO:choreographer.browser_async:Opening browser.
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmpw2wiaa69.
INFO:choreographer.browsers.chromium:Temporary directory at: /opt/tmp/tmpw2wiaa69
INFO:kaleido.kaleido:Conforming 1 to file:///opt/tmp/tmpf2vsa1cl/index.html
INFO:kaleido.kaleido:Waiting on all navigates
INFO:kaleido.kaleido:All navigates done, putting them all in queue.
INFO:kaleido.kaleido:Getting tab from queue (has 1)
INFO:kaleido.kaleido:Got BD6B
INFO:kaleido._kaleido_tab:Processing fig.png
INFO:kaleido._kaleido_tab:Sending big command for fig.png.
INFO:kaleido._kaleido_tab:Sent big command for fig.png.
INFO:kaleido.kaleido:Reloading tab BD6B before return.
INFO:kaleido.kaleido:Putting tab BD6B back (queue size: 0).
INFO:kaleido.kaleido:Waiting for all cleanups to finish.
INFO:kaleido.kaleido:Exiting Kaleido
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.browsers.chromium:Chromium init'ed with kwargs {}
INFO:choreographer.browsers.chromium:Found chromium path: /auto/sahara/namib/home/macgregor/miniconda3/envs/workflow_16s/lib/python3.10/site-packages/choreographer/cli/browser_exe/chrome-linux64/chrome
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmpbd3or_ow.
INFO:choreographer.browser_async:Opening browser.
INFO:choreographer.utils._tmpfile:Temp directory created: /opt/tmp/tmpxo3ama5e.
INFO:choreographer.browsers.chromium:Temporary directory at: /opt/tmp/tmpxo3ama5e
INFO:kaleido.kaleido:Conforming 1 to file:///opt/tmp/tmpbd3or_ow/index.html
INFO:kaleido.kaleido:Waiting on all navigates
INFO:kaleido.kaleido:All navigates done, putting them all in queue.
INFO:kaleido.kaleido:Getting tab from queue (has 1)
INFO:kaleido.kaleido:Got 10AA
INFO:kaleido._kaleido_tab:Processing fig.png
INFO:kaleido._kaleido_tab:Sending big command for fig.png.
INFO:kaleido._kaleido_tab:Sent big command for fig.png.
INFO:kaleido.kaleido:Reloading tab 10AA before return.
INFO:kaleido.kaleido:Putting tab 10AA back (queue size: 0).
INFO:kaleido.kaleido:Waiting for all cleanups to finish.
INFO:kaleido.kaleido:Exiting Kaleido
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:kaleido.kaleido:Cancelling tasks.
INFO:kaleido.kaleido:Exiting Kaleido/Choreo
INFO:choreographer.browser_async:Closing browser.
INFO:choreographer.utils._tmpfile:TemporaryDirectory.cleanup() worked.
INFO:choreographer.utils._tmpfile:shutil.rmtree worked.
INFO:choreographer.browsers.chromium:Chromium init'ed with kwargs {}
INFO:choreographer.browsers.chromium:Found chromium path: /auto/sahara/namib/home/macgregor/miniconda3/envs/workflow_16s/lib/python3.10/site-packages/choreographer/cli/browser_exe/chrome-linux64/chrome

In [4]:
data_object.metadata

,#sampleid,accession,base_count,broad_scale_environmental_context,broker_name,center_name,checklist,collection_date,collection_date_end,collection_date_start,...,submitted_ftp,submitted_galaxy,submitted_md5,tag,target_gene,target_subfragment,target_subfragment_length,tax_id,tax_lineage,facility_match
srr24892597,srr24892597,SAMN35709142,27865376,NaN,NCBI,Nanjing university,NaN,2020-09-27,2020-09-27,2020-09-26,...,NaN,NaN,NaN,env_geo;env_geo:terrestrial,16S rRNA,V3-V4,300.0,942017.0,1;2787823;12908;408169;410657;942017,False
srr10410732,srr10410732,SAMN13187583,26815342,temperate broadleaf forest,NCBI,The University of Auckland,NaN,2015,2015-12-31,2015-01-01,...,NaN,NaN,NaN,env_geo;env_geo:terrestrial,16S rRNA,V3-V4,300.0,410658.0,1;2787823;12908;408169;410657;410658,False
srr10406877,srr10406877,SAMN13188367,24195469,grassland area,NCBI,The University of Auckland,NaN,2016,2016-12-31,2016-01-01,...,NaN,NaN,NaN,env_geo;env_geo:terrestrial,16S rRNA,V3-V4,300.0,410658.0,1;2787823;12908;408169;410657;410658,False
srr20697351,srr20697351,SAMN30027168,14560574,NaN,NCBI,The university of kansas,NaN,2018-09-17,2018-09-17,2018-09-16,...,NaN,NaN,NaN,env_geo;env_geo:terrestrial,16S rRNA,V4,300.0,410658.0,1;2787823;12908;408169;410657;410658,False
err6691279,err6691279,SAMEA9569610,47578500,NaN,NaN,Centre for Structural and Functional Genomics,ERC000011,2019-07-28,2019-07-28,2019-07-27,...,ftp.sra.ebi.ac.uk/vol1/run/ERR669/ERR6691279/1...,ftp.sra.ebi.ac.uk/vol1/run/ERR669/ERR6691279/1...,6b2cd58425c5597ee0e53384c9ffa6e7;5ef2bdfe95c89...,env_tax;env_tax:freshwater;env_geo;env_geo:fre...,16S rRNA,V4,250.0,1647806.0,1;2787823;12908;408169;410657;1647806,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
srr10410959,srr10410959,SAMN13187198,49893104,Unknown biome,NCBI,The University of Auckland,NaN,2014,2014-12-31,2014-01-01,...,NaN,NaN,NaN,NaN,16S rRNA,V3-V4,300.0,410658.0,1;2787823;12908;408169;410657;410658,False
srr23872823,srr23872823,SAMN32683476,16267310,ENVO:01000222,NCBI,University of Colorado Boulder,NaN,2021-05,2021-05-31,2021-04-30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,410658.0,1;2787823;12908;408169;410657;410658,False
srr12457955,srr12457955,SAMN15768237,93863494,NaN,NCBI,The Univeristy of Auckland,NaN,2010-03-01,2010-03-01,2010-03-01,...,NaN,NaN,NaN,NaN,16S rRNA,V3-V4,250.0,410658.0,1;2787823;12908;408169;410657;410658,False
srr9892240,srr9892240,SAMN12437040,67773012,NaN,NCBI,University of Minnesota,NaN,2017-08-01,2017-08-01,2017-07-31,...,NaN,NaN,NaN,NaN,16S rRNA,V4,NaN,1076179.0,1;2787823;12908;408169;410657;1076179,False
srr23872975,srr23872975,SAMN31707993,11898196,ENVO_01000187,NCBI,University of Colorado Boulder,NaN,2021-05,2021-05-31,2021-04-30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,410658.0,1;2787823;12908;408169;410657;410658,False

In [5]:
data_object.tables

defaultdict(dict,
            {'raw': {'genus': 4484 x 16766 <class 'biom.table.Table'> with 789222 nonzero entries (1% dense)}})

In [7]:
transformer = DataProcessor(config, data_object)
transformer.run()

Output()

14:01:09 WARNING  Found and cleaned 369 anomalous IDs in 'phylum' table, merging any duplicates.

14:01:13 WARNING  Found and cleaned 843 anomalous IDs in 'class' table, merging any duplicates.

14:01:18 WARNING  Found and cleaned 1402 anomalous IDs in 'order' table, merging any duplicates.

14:01:31 WARNING  Found and cleaned 3589 anomalous IDs in 'family' table, merging any duplicates.

14:01:35 INFO     Generating presence/absence tables from raw data...

14:01:42 INFO     Synced table and metadata case-insensitively, retaining 5206 common samples.

         INFO     Synced table and metadata case-insensitively, retaining 5206 common samples.

         INFO     Synced table and metadata case-insensitively, retaining 5206 common samples.

14:01:47 INFO     Synced table and metadata case-insensitively, retaining 4935 common samples.

         INFO     Synced table and metadata case-insensitively, retaining 4935 common samples.

14:01:48 INFO     Synced table and metadata case-insensitively, retaining 4935 common samples.

14:01:52 INFO     Synced table and metadata case-insensitively, retaining 4935 common samples.

14:01:53 INFO     Synced table and metadata case-insensitively, retaining 4935 common samples.

         INFO     Synced table and metadata case-insensitively, retaining 4935 common samples.

14:01:58 INFO     Synced table and metadata case-insensitively, retaining 4935 common samples.

         INFO     Synced table and metadata case-insensitively, retaining 4935 common samples.

14:01:59 INFO     Synced table and metadata case-insensitively, retaining 4935 common samples.

14:02:08 INFO     Synced table and metadata case-insensitively, retaining 4935 common samples.

         INFO     Synced table and metadata case-insensitively, retaining 4935 common samples.

14:02:10 INFO     Synced table and metadata case-insensitively, retaining 4935 common samples.

         INFO     Final metadata saved to
                  /auto/sahara/namib/home/macgregor/amplicon/test/data/merged/metadata/final_metadata.tsv

Output()

In [8]:
data_object.metadata

,#sampleid,accession,base_count,broad_scale_environmental_context,broker_name,center_name,checklist,collection_date,collection_date_end,collection_date_start,...,submitted_ftp,submitted_galaxy,submitted_md5,tag,target_gene,target_subfragment,target_subfragment_length,tax_id,tax_lineage,facility_match
#sampleid,,,,,,,,,,,,,,,,,,,,,
srr10410732,srr10410732,SAMN13187583,26815342,temperate broadleaf forest,NCBI,The University of Auckland,NaN,2015,2015-12-31,2015-01-01,...,NaN,NaN,NaN,env_geo;env_geo:terrestrial,16S rRNA,V3-V4,300.0,410658.0,1;2787823;12908;408169;410657;410658,False
srr12457856,srr12457856,SAMN15768528,43664715,NaN,NCBI,The Univeristy of Auckland,NaN,2010-03-01,2010-03-01,2010-03-01,...,NaN,NaN,NaN,NaN,16S rRNA,V3-V4,250.0,410658.0,1;2787823;12908;408169;410657;410658,False
srr10405521,srr10405521,SAMN13188236,40452594,grassland area,NCBI,The University of Auckland,NaN,2016,2016-12-31,2016-01-01,...,NaN,NaN,NaN,env_geo;env_geo:terrestrial,16S rRNA,V3-V4,300.0,410658.0,1;2787823;12908;408169;410657;410658,False
srr16120197,srr16120197,SAMN21904415,17356780,NaN,NCBI,pda|ashoneyman,NaN,2019,2019-12-31,2019-01-01,...,NaN,NaN,NaN,env_geo;env_geo:freshwater;env_geo:terrestrial,16S rRNA,V4-V5,250.0,256318.0,1;2787823;12908;408169;256318,True
err4994118,err4994118,SAMEA7723610,3469946,marine benthic biome,NaN,University of California San Diego Microbiome ...,ERC000011,NaN,NaN,NaN,...,ftp.sra.ebi.ac.uk/vol1/run/ERR499/ERR4994118/1...,ftp.sra.ebi.ac.uk/vol1/run/ERR499/ERR4994118/1...,0873de47b40618ea5ecb844edcf47a83,env_tax;env_tax:marine;env_geo;env_geo:coastal...,16S rRNA,V4,NaN,412755.0,1;2787823;12908;408169;410657;412755,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
err4995466,err4995466,SAMEA7723910,9038255,Small river biome,NaN,University of California San Diego Microbiome ...,ERC000011,NaN,NaN,NaN,...,ftp.sra.ebi.ac.uk/vol1/run/ERR499/ERR4995466/1...,ftp.sra.ebi.ac.uk/vol1/run/ERR499/ERR4995466/1...,dd726a8fe5cd09a6032a0130b84089da,env_tax;env_tax:freshwater;env_geo;env_geo:fre...,16S rRNA,V4,NaN,556182.0,1;2787823;12908;408169;410657;556182,True
srr10407070,srr10407070,SAMN13189196,33068888,anthropogenic terrestrial biome,NCBI,The University of Auckland,NaN,2015,2015-12-31,2015-01-01,...,NaN,NaN,NaN,env_geo;env_geo:terrestrial,16S rRNA,V3-V4,300.0,410658.0,1;2787823;12908;408169;410657;410658,False
srr23872823,srr23872823,SAMN32683476,16267310,ENVO:01000222,NCBI,University of Colorado Boulder,NaN,2021-05,2021-05-31,2021-04-30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,410658.0,1;2787823;12908;408169;410657;410658,False
srr10410485,srr10410485,SAMN13187284,28189266,grassland area,NCBI,The University of Auckland,NaN,2013,2013-12-31,2013-01-01,...,NaN,NaN,NaN,env_geo;env_geo:terrestrial,16S rRNA,V3-V4,300.0,410658.0,1;2787823;12908;408169;410657;410658,False
srr12457955,srr12457955,SAMN15768237,93863494,NaN,NCBI,The Univeristy of Auckland,NaN,2010-03-01,2010-03-01,2010-03-01,...,NaN,NaN,NaN,NaN,16S rRNA,V3-V4,250.0,410658.0,1;2787823;12908;408169;410657;410658,False